MODEL_PATH = "artifacts/cnn.pt"
LABELS_PATH = MODEL_PATH + ".labels.json"
CSV_PATH = "data/urbansound8k.csv"
DATASET_ROOT = "data/UrbanSound8K"

SAMPLE_RATE = 22050
DURATION = 4.0
N_MELS = 128
N_FFT = 1024
HOP_LENGTH = 512

# Streaming defaults (match training window for accuracy)
STREAM_DURATION = 4.0
STREAM_N_MELS = N_MELS

# SpecAugment defaults (optional)
SPEC_AUGMENT = True
SPEC_AUGMENT_STRENGTH = 1.0
TIME_MASK_PARAM = 20
FREQ_MASK_PARAM = 8
NUM_TIME_MASKS = 2
NUM_FREQ_MASKS = 2

# Audio augmentation (optional)
AUG_TIME_STRETCH = True
TIME_STRETCH_RANGE = (0.9, 1.1)
AUG_PITCH_SHIFT = True
PITCH_SHIFT_STEPS = (-2.0, 2.0)
AUG_NOISE = True
NOISE_STD = 0.005
AUG_TIME_SHIFT = True
TIME_SHIFT_MAX_FRACTION = 0.1

# RMS normalization (optional)
RMS_NORMALIZE = True
RMS_TARGET = 0.1

BATCH_SIZE = 32
LEARNING_RATE = 1e-3
EPOCHS = 40
WEIGHT_DECAY = 1e-4
USE_CLASS_WEIGHTS = True
EARLY_STOPPING_PATIENCE = 6
SCHEDULER_PATIENCE = 3
SCHEDULER_FACTOR = 0.5
SEED = 67
